# Generated by Django 2.2.7 on 2019-11-09 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webface', '0003_auto_20191109_2233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitor',
            old_name='fake_user_id',
            new_name='real_user_id',
        ),
    ]
