# Generated by Django 2.2.7 on 2019-11-10 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webface', '0005_auto_20191110_0838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='streamsource',
            old_name='event',
            new_name='event_id',
        ),
    ]
