# Generated by Django 2.2.7 on 2019-11-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webface', '0007_auto_20191110_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userface',
            name='face_id',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='face_id',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
